uploads = []
generated = []

[[outputs]]
id = "l9p2ekF4hTh5PM_G2y7dc"
uri = "file://OBTrack_iOS.tar.gz"
type = "unspecified"
title = "OBTrack iOS — full project (Mac / Xcode)"

[[outputs]]
id = "RvWQvFaExV3wxVWNvKAvD"
uri = "file://OBTrack_Gateway.tar.gz"
type = "unspecified"
title = "OBTrack Gateway — standalone (Ubuntu server)"
