// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/obtrack-app/MainIdle.tsx": () => import("../components/mockups/obtrack-app/MainIdle.tsx"),
  "./components/mockups/obtrack-app/MainTracking.tsx": () => import("../components/mockups/obtrack-app/MainTracking.tsx"),
  "./components/mockups/obtrack-app/TrimSheet.tsx": () => import("../components/mockups/obtrack-app/TrimSheet.tsx")
};
